---
title: "Locating Dimensions of Women’s Empowerment in Family Planning in Burkina Faso"
description: |
  A short description of the post.
author: Tayler Nelson
date: 11-20-2020
output:
  distill::distill_article:
    self_contained: false
bibliography: citations/test2.bib
draft: true
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

[@Lipton2015-rs]

Women’s “empowerment,” defined by Naila Kabeer[1] as “the expansion of people’s ability to make strategic life choices in a context where this ability was previously denied to them,” has been shown[2] to be associated with greater birth spacing, lower fertility, and lower rates of unplanned pregnancy. Yet scholars disagree[3] on how to measure women’s empowerment, and meanings of empowerment can shift across geographic and cultural contexts.

IPUMS PMA’s family planning surveys include variables that can help researchers investigate dimensions of women’s empowerment in family planning. All samples include indicators of women’s knowledge about family planning methods. Many survey rounds dig deeper, collecting data that can be used by researchers and policymakers.

The Burkina Faso 2018 Round 6 survey includes a range of variables measuring family planning attitudes, beliefs, and decision-making dynamics that relate to women’s empowerment. I used a weighted polychoric factor analysis[4] to investigate women’s empowerment in family planning in Burkina Faso. Factor analysis can help researchers reduce a large number of observed variables by identifying similar response patterns among observed variables and grouping them into a smaller set of underlying variables, or factors. Through analyzing how variables are grouped and the strength and signs of coefficients within these groups, researchers can glean insight into which sets of observed variables might be best at measuring an unobserved construct such as women’s empowerment.

After reviewing the literature on women’s empowerment in family planning, I selected nineteen PMA variables to capture dimensions of women’s empowerment in family planning in Burkina Faso. These included social context variables (URBAN, WEALTHQ, EDUCATTGEN), whether the woman is a current/recent family planning user (FPCURRECUSER), whether the woman has heard of family planning on television (FPTVHR) or radio (FPRADIOHR), and belief and attitude variables that use a Likert scale to measure how much the woman agrees with a particular statement about family planning (SAFEDISCKID, SAFEDISCFP, CONFLICTFP, DAMRELFP, NEGOTIATEKIDS, BELIEFCARRYPREG, BELIEFDAUPREG, AGREESPACE, AGREELIMIT, AGREECONTR, AGREEFP, AGREEPARTFP). I also combined two variables that measure who is the primary decision-maker in deciding to use (FPDECIDER) or not to use (DECNOFPUSE) family planning into a single ordinal variable (DECIDER) that reports how much input a woman has in the couple’s family planning decisions. I excluded not in universe (NIU) and missing cases as well as females who were not married or partnered; my analytical sample contained 1,686 women. All analyses applied appropriate sampling weights.

I retained three factors[5] and analyzed which characteristics or beliefs relate to each underlying factor by examining variable groupings and factor loadings. Table 1 displays all factor loadings above 0.3 for each variable. Looking at high factor loadings can help researchers identify underlying factors. I have marked moderate and strong factor loadings[6] in the table with an asterisk(*).

Factor 1 includes the majority of attitude and belief variables. I looked at similarities and differences between variables and their factor loadings[7] to interpret this factor. Variables with high factor loadings all relate to good spousal communication around family planning. For instance, SAFEDISCFP, which reports how much the respondent agrees that it is safe to discuss family planning with her partner, has the highest factor loading. Variables related to spousal conflict, such as CONFLICTFP, have weak but negative factor loadings. Together, these results indicate that Factor 1 might be a latent measure of spousal communication. Alternative interpretations are possible: for example, it might be that this factor simply represents support for family planning, and variables with high factor loadings are the most useful observed indicators of this factor.

For Factor 2, the high factor loadings for URBAN and WEALTHQ suggest that this factor indicates socioeconomic status. The variable for whether the woman has heard about family planning on TV loads moderately highly on this factor; this seems logical assuming TV ownership is a reflection of socioeconomic status.

For Factor 3, the factor loadings are relatively small except for the loading for the belief that women should not get pregnant if she is still carrying a child on her back. In line with a Burkina Faso 2014 report that found popular acceptance of family planning for spacing rather than limiting births and stigma around women who have children too closely together, this factor might indicate adherence to traditional Burkina Faso beliefs around family planning. AGREESPACE, which reports the respondent’s agreement with couples using contraception to space the birth of their children, also loads on this factor. This factor may indicate value of traditional beliefs or more explicit support for child spacing.

This factor analysis indicates several dimensions of empowerment for understanding family planning in Burkina Faso and suggests a handful of important variables (those with high factor loadings) users may be interested in including in analyses of female empowerment. It also highlights other areas to explore. For example, I was surprised that DECIDER was not strongly associated with any single factor (though iterations of this analysis that measured joint decision-making showed high factor loading alongside the other socioeconomic status variables in Factor 2). Researchers may want to use PMA data to investigate whether spousal communication, socioeconomic status, and geographically-specific traditional beliefs remain important factors in family planning variables across different countries and years, or look further into how decision-making might align with these factors.